const SEAT_MAP_BRANCH_TYPE = "seat-dag-continuity-v2";

const EVENT_KIND_REFERENT_CREATED = "referent-created";
const EVENT_KIND_SEAT_OCCUPIED = "seat-occupied";
const EVENT_KIND_SEAT_VACATED = "seat-vacated";
const EVENT_KIND_SEAT_POSITION_CHANGED = "seat-position-changed";
const EVENT_KIND_EXTERNAL_SEAT_PROJECTION_ADMITTED = "external-seat-projection-admitted";
const EVENT_KIND_EXTERNAL_REFERENT_ADMITTED = "external-referent-admitted";
const EVENT_KIND_CHECKPOINT_ADMITTED = "checkpoint-admitted";
const EVENT_KIND_CONTINUITY_SEED_ADMITTED = "continuity-seed-admitted";
const EVENT_KIND_JOIN_POINT_ADMITTED = "join-point-admitted";

const SEAT_MAP_EVENT_KINDS = Object.freeze([
  EVENT_KIND_REFERENT_CREATED,
  EVENT_KIND_SEAT_OCCUPIED,
  EVENT_KIND_SEAT_VACATED,
  EVENT_KIND_SEAT_POSITION_CHANGED,
  EVENT_KIND_EXTERNAL_SEAT_PROJECTION_ADMITTED,
  EVENT_KIND_EXTERNAL_REFERENT_ADMITTED,
  EVENT_KIND_CHECKPOINT_ADMITTED,
  EVENT_KIND_CONTINUITY_SEED_ADMITTED,
  EVENT_KIND_JOIN_POINT_ADMITTED,
]);

module.exports = {
  SEAT_MAP_BRANCH_TYPE,
  EVENT_KIND_REFERENT_CREATED,
  EVENT_KIND_SEAT_OCCUPIED,
  EVENT_KIND_SEAT_VACATED,
  EVENT_KIND_SEAT_POSITION_CHANGED,
  EVENT_KIND_EXTERNAL_SEAT_PROJECTION_ADMITTED,
  EVENT_KIND_EXTERNAL_REFERENT_ADMITTED,
  EVENT_KIND_CHECKPOINT_ADMITTED,
  EVENT_KIND_CONTINUITY_SEED_ADMITTED,
  EVENT_KIND_JOIN_POINT_ADMITTED,
  SEAT_MAP_EVENT_KINDS,
};
